routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\AuthController@handleProviderCallback');

Route::post('post', 'PostController@store')->middleware('can:store,App\Post');
Route::get('best-of/{param}', 'PostController@bestOf');
Route::get('najbolje/{param}', 'PostController@showBestOf');
Route::post('post/favorite/{id}', 'PostFavoritesController@store');
Route::post('post/vote', 'PostVotesController@store');
Route::get('objava/{id}', 'PostController@show');
Route::get('post-share', 'PostController@share');
Route::delete('post/{id}', 'PostController@destroy');
Route::patch('post/restore/{id}', 'PostController@restore');
Route::patch('post/{id}', 'PostController@update')->middleware('can:update,App\Post');
// Route::get('najbolje')

Route::get('profil/{slug}', 'UserController@show');
Route::post('profile/edit', 'UserController@update');
Route::post('profil/follow/{id}', 'UserController@follow');
Route::get('new-follow', 'UserController@getFollow');

Route::get('otkrijte-kategorije/{filter?}', 'CategoryController@index');
Route::get('otkrijte-korisnike', 'UserController@index')->middleware('auth');

Route::get('blokirane-kategorije', 'CategoryController@blockedCategories')->middleware('auth');
Route::get('moje-kategorije', 'CategoryController@ownedCategories')->middleware('auth');

Route::post('kategorija/subscribe', 'CategoryController@subscribe');
Route::get('kategorija/{slug}/moderator', 'CategoryController@edit')->middleware('moderator');
Route::get('kategorija/{slug}/{filter?}', 'CategoryController@show')->name('category.show');
Route::post('kategorija', 'CategoryController@store')->middleware('can:store,App\Category');
Route::post('kategorija/{id}', 'CategoryController@update')->middleware('can:update,App\Category');
Route::post('category/block/{id}', 'CategoryController@block');
Route::post('category/unblock/{id}', 'CategoryController@unblock');

Route::get('comments/{id}', 'CommentController@index');
Route::post('comment', 'CommentController@store')->middleware('can:store,App\Comment');
Route::post('comment/vote', 'CommentController@vote');

Route::post('search', 'SearchController@ajax');
Route::post('search/categories', 'SearchController@categories');

Route::post('validation/username', 'ValidationController@username');
Route::post('validation/email', 'ValidationController@email');
Route::post('validation/category-name', 'ValidationController@categoryName');
Route::post('validation/image', 'ValidationController@image');
Route::post('validation/post', 'ValidationController@post');
Route::post('validation/edit-username', 'ValidationController@editUsername');

Route::view('polisa-privatnosti', 'privacy-policy');

Route::post('feedback', 'FeedbackController@store');
Route::post('report', 'ReportController@store');

Route::post('notifications/all-read', 'NotificationsController@update');

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function() {
	Route::get('/', 'AdminController@dashboard')->name('Dashboard');

	Route::get('users', 'AdminController@users')->name('Users');
	Route::post('users/ban/{id}', 'UserController@banUser');
	Route::get('users/unban/{id}', 'UserController@unbanUser');

	Route::get('posts', 'AdminController@posts')->name('Posts');
	Route::get('posts/delete/{id}', 'PostController@delete');

	Route::get('stack-posts', 'AdminController@stackPosts')->name('Stack Posts');
	Route::post('submit-stack-posts', 'AdminController@submitStackPosts');

	Route::get('categories', 'AdminController@categories')->name('Categories');
	Route::post('categories/recommended', 'CategoryController@toggleRecommended');
	Route::get('categories/approve/{id}', 'CategoryController@approve');
	Route::get('categories/reject/{id}', 'CategoryController@reject');
	Route::get('categories/delete/{id}', 'CategoryController@delete');

	Route::get('medals', 'AdminController@medals')->name('Medals');

	Route::get('reports', 'AdminController@reports')->name('Reports');
});

Route::get('//{filter?}', 'PostController@index')
		->where('filter', 'popularno|novo|top|kategorije|korisnici');

app/Post.php
<?php

namespace App;

use App\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Laravel\Scout\Searchable;

class Post extends Model
{
    use Searchable;
    use SoftDeletes;

    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        return array_only($this->toArray(), ['id', 'body']);
    }

    protected $fillable = [
    	'body', 'image', 'video', 'nsfw', 'best_of', 'category_id', 'user_id', 'created_at'
    ];

    protected $appends = ['diffCreatedAt'];

    protected $dates = ['deleted_at'];

    public function getDiffCreatedAtAttribute()
    {
        return Carbon::parse($this->attributes['created_at'])->diffForHumans();
    }

    public function user()
    {
    	return $this->belongsTo('App\User');
    }

    public function category()
    {
    	return $this->belongsTo('App\Category');
    }
    
    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    public function votes()
    {
        return $this->belongsToMany('App\User', 'votes')
            ->withPivot('vote')
            ->withTimestamps();
    }

    public function votedBy(User $user)
    {
        return $this->votes()->where('user_id', $user->id)->pluck('vote');
    }

    public function favorites()
    {
        return $this->belongsToMany('App\User', 'favorites');
    }

    public function scopeEagerLoad($query)
    {
        return $query
            ->with(['user', 'category', 'votes', 'favorites'])
            ->withCount([
                'favorites',
                'comments',
                'votes as upvotes_count' => function ($query) {
                    $query->where('vote', 1);
                },
                'votes as downvotes_count' => function ($query) {
                    $query->where('vote', -1);
                }
            ]);
    }

    public function scopeNotBlocked($query)
    {
        if(Auth::guest()) return;
        
        $blocked = 
            Auth::user()
                ->categories()
                ->where('blocked', 1)
                ->get()
                ->pluck(['id'])
                ->toArray();

        return $query->whereNotIn('category_id', $blocked);                    
    }

    public function scopeFilter($query, $filter)
    {
        switch ($filter) {
            case 'novo':
                return $query->latest();
                break;
            case 'top':
                return $query->orderBy('upvotes_count', 'desc');
                break;
            case 'kategorije':
                if(auth()->guest()) return; 
                
                $subs = auth()->user()->categories()
                            ->where('subscribed', 1)
                            ->get()
                            ->pluck('id')
                            ->toArray();

                return $query->whereIn('category_id', $subs)
                            ->latest();

                break;
            case 'korisnici':
                if(auth()->guest()) return; 
                
                $subs = auth()->user()->following()
                            ->get()
                            ->pluck('id')
                            ->toArray();

                return $query->whereIn('user_id', $subs)
                            ->latest();
                break;
            // case: popularno
            default:
                /*
                 * SEE: https://medium.com/hacking-and-gonzo/how-hacker-news-ranking-algorithm-works-1d9b0cf2c08d
                 * 0.1 is when upvotes and downvotes are the same count,
                 * so it wont be 0/POWER.... which would be 0
                 */ 
                return $query->orderByRaw(
                    '((upvotes_count - downvotes_count + 0.1) / POWER(TIMEDIFF(NOW(), created_at) + 2, 1.8)) desc'
                );
        }
    }

    // obrisati?
    public function scopeBestOf($query, $param)
    {
        switch ($param) {
            case 'day':
                return $query->whereBetween(
                    'created_at', [Carbon::yesterday(), Carbon::today()]
                );
                break;
            case 'week':
                return $query->whereBetween(
                    'created_at', [Carbon::now()->startOfWeek()->subWeek(), Carbon::now()->endOfWeek()->subWeek()]
                );
                break;
            case 'month':
                return $query->whereBetween(
                    'created_at', [Carbon::now()->startOfMonth()->subMonth(), Carbon::now()->endOfMonth()->subMonth()]
                );
                break;
        }
    }

    public function scopeGetBestOf($query, $param)
    {
        switch ($param) {
            case 'day':
                return $query->where('best_of', 'day');
                break;
            case 'week':
                return $query->where('best_of', 'week');
                break;
            case 'month':
                return $query->where('best_of', 'month');
                break;
        }
    }
}

resources/views/admin/categories.blade.php
@extends('admin.master')

@section('content')

    <h3>Recommended categories</h3>
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>Image</th>
            <th>Number</th>
            <th>Name</th>
            <th>Description</th>
            <th>NSFW</th>
            <th>Cover Box</th>
            <th>Pictures</th>
            <th>Videos</th>
            <th>Created at</th>
        </tr>
        @foreach($recommended as $category)
        <tr>
            <td><img width="80" height="80" src="{{ asset($category->image) }}"></td>
            <td> {{ $loop->iteration }} </td>
            <td> {{ $category->name }} </td>
            <td> {{ $category->description }}</td>
            <td> {{ $category->nsfw }} </td>
            <td> {{ $category->cover_box }} </td>
            <td> {{ $category->pictures }} </td>
            <td> {{ $category->videos }} </td>
            <td> 
                {{ \Carbon\Carbon::parse($category->updated_at)->diffForHumans() }}
            </td>
        </tr>
        @endforeach
    </table>

    <h3>All categories</h3>
	<div class="row">
	    <div class="col-lg-12">
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    {{-- <table class="table table-striped table-bordered table-hover" id="dataTable"> --}}
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>NSFW</th>
                                <th>Cover Box</th>
                                <th>Pictures</th>
                                <th>Videos</th>
                                <th>Created at</th>
                                <th>Approved</th>
                                <th>Izabrano</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                        @foreach($categories as $category)

                            <tr>
                                <td> {{ $category->name }} </td>
                                <td> {{ $category->nsfw }} </td>
                                <td> {{ $category->cover_box }} </td>
                                <td> {{ $category->pictures }} </td>
                                <td> {{ $category->videos }} </td>
                                <td> 
                                	{{ \Carbon\Carbon::parse($category->updated_at)->diffForHumans() }}
                                </td>
                                <td> 
                                	@if($category->approved === 0)
                                		Waiting
                                	@elseif($category->approved === 1)
                                		Rejected
                                	@else
                                		Approved
									@endif
                                </td>
                                <td>
                                    <input class="toggleRecommended" name="recommended" type="checkbox" data-id="{{ $category->id }}" @if($category->recommended === 1) checked="true" @endif>
                                </td>
                                <td>
                                	<a href="categories/approve/{{ $category->id }}">
                                		<i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                                	</a>&nbsp;
                                	<a class="text-danger" href="categories/reject/{{ $category->id }}">
                                		<i class="fa fa-thumbs-o-down" aria-hidden="true"></i>
                                	</a>&nbsp;
                                	<a class="text-muted" href="categories/delete/{{ $category->id }}">
                                		<i class="fa fa-trash" aria-hidden="true"></i>
                                	</a>
                                </td>
                            </tr>

						@endforeach

                        </tbody>
                    </table>
                </div>
            </div>
	    </div>
	</div>

@endsection

@section('external-js')
<script>
    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('.toggleRecommended').click(function (e) {

            id = $(this).data('id');
            recommended = 0;

            if ($(this).is(":checked")) 
                recommended = 1;

            var data = {
                'id': id,
                'recommended': recommended
            };
            
            $.post('/admin/categories/recommended', data, function (data) {
                console.log('done. make append');
            });
        });
    });
</script>
@endsection

resources/views/admin/dashboard.blade.php
@extends('admin.master')

@section('content')


	<div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-users fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">2</div>
                        <div>Registered Users</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-archive fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">3</div>
                        <div>Posts</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-star fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">4</div>
                        <div>Original Posts</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-signal fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">N/A</div>
                        <div>Daily Visits</div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/master.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="robots" content="noindex">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>Startmin Admin Panel</title>

        <!-- Bootstrap Core CSS -->
        <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{{ asset('css/startmin.css') }}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">

        <!-- DataTable CSS CDN -->
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">

        <!-- Font Awesome -->
        <script src="https://use.fontawesome.com/94a3cab706.js"></script>

        <!-- DataTables CSS -->
        <link href="{{ asset('css/dataTables/dataTables.bootstrap.css') }}" rel="stylesheet">
        {{-- DataTables Responsive CSS --}}
        <link href="{{ asset('css/dataTables/dataTables.responsive.css') }}" rel="stylesheet">

        @yield('external-css')
    </head>
    <body>

        <div id="wrapper">
            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="navbar-header">
                    <a class="navbar-brand" href="http://secondtruth.github.io/startmin/pages/index.html">Startmin</a>
                </div>

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <ul class="nav navbar-nav navbar-left navbar-top-links">
                    <li><a href="/"><i class="fa fa-home fa-fw"></i> Website</a></li>
                </ul>

                <ul class="nav navbar-right navbar-top-links">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i> {{ Auth::user()->name }} <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="{{ route('logout') }}" 
                                onclick="event.preventDefault(); 
                                document.getElementById('logout-form').submit();">
                                    <i class="fa fa-sign-out fa-fw"></i> Logout</a>
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" 
                                method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                                        
                        </ul>
                    </li>
                </ul>
                <!-- /.navbar-top-links -->

                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li>
                                <a href="{{ url('admin') }}" class="{{ Request::is('admin') ? 'active' : '' }}">
                                    <i class="fa fa-dashboard fa-fw"></i> Dashboard
                                </a>
                            </li>
                            <li>
                                <a href="{{ url('admin/users') }}" class="{{ Request::is('admin/users') ? 'active' : '' }}">
                                    <i class="fa fa-users fa-fw"></i> Users
                                </a>
                            </li>
                            <li>
                                <a href="{{ url('admin/posts') }}" class="{{ Request::is('admin/posts') ? 'active' : '' }}">
                                    <i class="fa fa-pencil fa-fw"></i> Posts
                                </a>
                            </li>
                            <li>
                                <a href="{{ url('admin/stack-posts') }}" class="{{ Request::is('admin/stack-posts') ? 'active' : '' }}">
                                    <i class="fa fa-pencil fa-fw"></i> Stack Posts
                                </a>
                            </li>
                            <li>
                                <a href="{{ url('admin/categories') }}" class="{{ Request::is('admin/categories') ? 'active' : '' }}">
                                    <i class="fa fa-archive fa-fw"></i> Categories
                                </a>
                            </li>
                            <li>
                                <a href="{{ url('admin/medals') }}" class="{{ Request::is('admin/medals') ? 'active' : '' }}">
                                    <i class="fa fa-circle-o-notch fa-fw"></i> Medals
                                </a>
                            </li>
                            <li>
                                <a href="{{ url('admin/reports') }}" class="{{ Request::is('admin/reports') ? 'active' : '' }}">
                                    <i class="fa fa-flag fa-fw"></i> Reports
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <div id="page-wrapper">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header"> {{ Route::currentRouteName() }} </h1>
                    </div>
                </div>
                <div class="row">


                    @yield('content')


                </div>
            </div>
        </div>

        <!-- JQuery CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

        
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
        <!-- DataTables JavaScript -->
        <script src="{{ asset('js/dataTables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ asset('js/dataTables/dataTables.bootstrap.min.js') }}"></script>
        <script>
            $(document).ready(function(){
                $('#dataTable').DataTable();
            });
        </script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{{ asset('js/bootstrap.min.js') }}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="{{ asset('js/startmin.js') }}"></script>

        @yield('external-js')

    </body>
</html>

resources/views/admin/medals.blade.php
@extends('admin.master')

@section('content')



@endsection

resources/views/admin/posts.blade.php
@extends('admin.master')

@section('content')

	<div class="row">
	    <div class="col-lg-12">
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTable">
                        <thead>
                            <tr>
                                <th>Post</th>
                                <th>Posted by</th>
                                <th>Original</th>
                                <th>Category</th>
                                <th>Upvotes</th>
                                <th>Downvotes</th>
                                <th>Favorites</th>
                                <th>Created at</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                        @foreach($posts as $post)

                            <tr>
                                <td class="col-md-3">{{ $post->body }}</td>
                                <td>{{ $post->user->username }}</td>
                                <td>{{ $post->original }}</td>
                                <td>{{ $post->category->name }}</td>
                                <td>{{ $post->upvotes_count }}</td>
                                <td>{{ $post->downvotes_count }}</td>
                                <td>{{ $post->favorites_count }}</td>
                                <td>
                                	{{ \Carbon\Carbon::parse($post->created_at)->diffForHumans() }}
                                </td>
                                <td>
                                	<a class="text-danger" href="posts/delete/{{ $post->id }}">
                                		<i class="fa fa-trash" aria-hidden="true"></i>
                                	</a>
                                </td>
                            </tr>

						@endforeach

                        </tbody>
                    </table>
                </div>
            </div>
	    </div>
	</div>

@endsection

resources/views/admin/reports.blade.php
@extends('admin.master')

@section('content')

	<div class="row">
	    <div class="col-lg-12">
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table id="dataTable" class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Body</th>
                                <th>Reportable_type</th>
                                <th>Reportable_id</th>
                                <th>User ID</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($reports as $report)
                            <tr>				
                				<td>{{ $report->id }}</td>
                				<td>{{ $report->body }}</td>
                                <td>{{ $report->reportable_type }}</td>
                				<td>{{ $report->reportable_id }}</td>
                				<td>{{ $report->user_id }}</td>
                				<td>{{ $report->created_at }}</td>
                			</tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
	    </div>
	</div>

@endsection